import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async headers(){return [
    {source:'/releases/tingye-ios-1.7.6-build33.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.7.6-build33.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.7.5-build32.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.7.5-build32.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/wereader-1.6.4-16005.apk',headers:[{key:'Content-Type',value:'application/vnd.android.package-archive'},{key:'Content-Disposition',value:'attachment; filename="wereader-1.6.4-16005.apk"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.7.4-build31.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.7.4-build31.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.7.3-build30.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.7.3-build30.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.7.1-build26.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.7.1-build26.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.7.2-build27.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.7.2-build27.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.7.7-build34.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.7.7-build34.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.7.0-build24.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.7.0-build24.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.6.4-build23.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.6.4-build23.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.6.3-build22.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.6.3-build22.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.6.1-build21.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.6.1-build21.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.5.1-build20.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.5.1-build20.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/wereader-1.6.3-16004.apk',headers:[{key:'Content-Type',value:'application/vnd.android.package-archive'},{key:'Content-Disposition',value:'attachment; filename="wereader-1.6.3-16004.apk"'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/wereader-1.6.2-16003.apk',headers:[{key:'Content-Type',value:'application/vnd.android.package-archive'},{key:'Content-Disposition',value:'attachment; filename="wereader-1.6.2-16003.apk"'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/wereader-1.6.1-16002.apk',headers:[{key:'Content-Type',value:'application/vnd.android.package-archive'},{key:'Content-Disposition',value:'attachment; filename="wereader-1.6.1-16002.apk"'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/wereader-1.6.0-16001.apk',headers:[{key:'Content-Type',value:'application/vnd.android.package-archive'},{key:'Content-Disposition',value:'attachment; filename="wereader-1.6.0-16001.apk"'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/wereader-1.5.1-15002.apk',headers:[{key:'Content-Type',value:'application/vnd.android.package-archive'},{key:'Content-Disposition',value:'attachment; filename="wereader-1.5.1-15002.apk"'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/wereader-1.5.0-15001.apk',headers:[{key:'Content-Type',value:'application/vnd.android.package-archive'},{key:'Content-Disposition',value:'attachment; filename="wereader-1.5.0-15001.apk"'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/wereader-1.3.0-13001.apk',headers:[{key:'Content-Type',value:'application/vnd.android.package-archive'},{key:'Content-Disposition',value:'attachment; filename="wereader-1.3.0-13001.apk"'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/wereader-1.4.0-14001.apk',headers:[{key:'Content-Type',value:'application/vnd.android.package-archive'},{key:'Content-Disposition',value:'attachment; filename="wereader-1.4.0-14001.apk"'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.3.1-build15.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.3.1-build15.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.3.2-build17.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.3.2-build17.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.3.3-build18.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.3.3-build18.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
    {source:'/releases/tingye-ios-1.4.0-build19.ipa',headers:[{key:'Content-Type',value:'application/octet-stream'},{key:'Content-Disposition',value:'attachment; filename="tingye-ios-1.4.0-build19.ipa"'},{key:'Cache-Control',value:'public, max-age=31536000, immutable'},{key:'X-Content-Type-Options',value:'nosniff'}]},
  ];},
};

export default nextConfig;
