import { DisplayText as Text } from '../components/DisplayText';
import {useState} from 'react';
import {Pressable,ScrollView,StyleSheet,TextInput,View} from 'react-native';
import {signIn,type Session,type Credentials} from './client';
import type {ReadingTheme} from './themes';
import Icon from '../components/Icon';
import {brand} from '../theme/tokens';
export default function AccountScreen({colors,onSignedIn}:{colors:ReadingTheme;onSignedIn:(value:Session)=>void}){
 const [mode,setMode]=useState<Credentials['action']>('login'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[invite,setInvite]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [result,setResult]=useState<(Session&{recoveryCode?:string})|null>(null),[saved,setSaved]=useState(false);
 const action=mode==='login'?'登录':mode==='register'?'创建账号':'重置密码';
 const submit=async()=>{if(busy)return;if(!/^[A-Za-z0-9_]{3,24}$/.test(username.trim())){setError('用户名需要 3–24 位字母、数字或下划线。');return;}if(password.length<10||password.length>128){setError('密码需要 10–128 位字符。');return;}setBusy(true);setError('');try{const next=await signIn({action:mode,username,password,invite:invite.trim(),recoveryCode:code.trim()});setPassword('');setCode('');if(next.recoveryCode)setResult(next);else onSignedIn(next);}catch(e){setError(e instanceof Error?e.message:'登录失败，请重试。');}finally{setBusy(false);}};
 const field=(label:string,value:string,setValue:(v:string)=>void,secret=false,maxLength=128)=><View style={{gap:8}}><Text style={{color:colors.text,fontSize:15}}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={setValue} secureTextEntry={secret} autoCapitalize="none" autoCorrect={false} maxLength={maxLength} style={[styles.input,{color:colors.text,borderColor:colors.line,backgroundColor:colors.surface}]} placeholderTextColor={colors.muted} autoComplete={secret?(mode==='login'?'current-password':'new-password'):label==='用户名'?'username':'off'}/></View>;
 return <ScrollView keyboardShouldPersistTaps="handled" automaticallyAdjustKeyboardInsets contentContainerStyle={styles.page}>
  <View style={styles.brand}>
   <View style={[styles.logo,{backgroundColor:colors.accent}]}><Icon name="headphones" size={30} color="#C9A259"/></View>
   <Text style={{color:colors.text,fontSize:34,fontWeight:'700',fontFamily:brand.serif,letterSpacing:4,marginTop:14}}>听页</Text>
   <Text style={{color:colors.muted,fontSize:13,marginTop:6,letterSpacing:1}}>读一页，也听一页</Text>
  </View>
  <View style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.line}]}>
   {!result&&mode!=='recover'&&<View style={[styles.segment,{backgroundColor:colors.background,borderColor:colors.line}]}>{(['login','register'] as const).map(m=><Pressable key={m} accessibilityRole="tab" accessibilityState={{selected:mode===m}} disabled={busy} onPress={()=>{setMode(m);setError('');}} style={[styles.segmentItem,mode===m&&{backgroundColor:colors.surface}]}><Text style={{color:mode===m?colors.text:colors.muted,fontWeight:mode===m?'700':'500',fontSize:15}}>{m==='login'?'登录':'邀请码注册'}</Text></Pressable>)}</View>}
   {result?<><Text style={[styles.title,{color:colors.text}]}>保存你的恢复码</Text><Text style={{color:colors.muted,lineHeight:24}}>忘记密码时，用它找回账号。请长按复制，保存到安全的地方；此页面关闭后不再显示。</Text><Text selectable style={[styles.code,{color:colors.text,backgroundColor:colors.highlight}]}>{result.recoveryCode}</Text><Pressable accessibilityRole="checkbox" accessibilityState={{checked:saved}} onPress={()=>setSaved(!saved)} style={{paddingVertical:16}}><Text style={{color:colors.text}}>{saved?'☑':'☐'} 我已妥善保存恢复码</Text></Pressable><Pressable disabled={!saved} onPress={()=>onSignedIn(result)} style={[styles.primary,{backgroundColor:colors.accent,opacity:saved?1:.4}]}><Text style={{color:colors.onAccent,fontWeight:'600'}}>进入书架</Text></Pressable></>:<>
   <Text style={[styles.title,{color:colors.text}]}>{mode==='login'?'登录你的书架':mode==='register'?'创建听页账号':'找回账号'}</Text><Text style={{color:colors.muted,lineHeight:23}}>{mode==='login'?'使用新网站的用户名和密码，在 App 内继续阅读。':mode==='register'?'输入一次性邀请码注册，无需手机号或第三方账号。':'使用注册时保存的恢复码，设置新密码。'}</Text>
   {field('用户名',username,setUsername,false,24)}{field(mode==='recover'?'新密码':'密码',password,setPassword,true)}{mode==='register'&&field('邀请码',invite,setInvite,false,64)}{mode==='recover'&&field('恢复码',code,setCode,false,64)}
   {!!error&&<Text accessibilityRole="alert" style={{color:'#B4443C',lineHeight:22}}>{error}</Text>}
   <Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()} style={[styles.primary,{backgroundColor:colors.accent,opacity:busy?.5:1}]}><Text style={{color:colors.onAccent,fontSize:17,fontWeight:'600',alignSelf:'stretch',textAlign:'center',paddingHorizontal:8}}>{busy?'正在处理…':action}</Text></Pressable>
   <View style={{flexDirection:'row',justifyContent:'center'}}><Pressable disabled={busy} onPress={()=>{setMode(mode==='recover'?'login':'recover');setError('');}} style={styles.link}><Text style={{color:colors.accent,fontWeight:'600'}}>{mode==='recover'?'返回登录':'忘记密码？用恢复码找回'}</Text></Pressable></View></>}
  </View><View style={{flexDirection:'row',justifyContent:'center',alignItems:'center',gap:6}}><Icon name="lock" size={14} color={colors.muted}/><Text style={{color:colors.muted,textAlign:'center',lineHeight:23,fontSize:12}}>本机保存书籍 · 多设备同步进度</Text></View>
 </ScrollView>;
}
const styles=StyleSheet.create({page:{flexGrow:1,padding:22,gap:20,justifyContent:'center'},brand:{alignItems:'center'},logo:{width:68,height:68,borderRadius:22,alignItems:'center',justifyContent:'center',overflow:'hidden'},segment:{flexDirection:'row',borderRadius:16,padding:4,borderWidth:StyleSheet.hairlineWidth},segmentItem:{flex:1,height:40,borderRadius:12,alignItems:'center',justifyContent:'center'},card:{width:'100%',maxWidth:460,alignSelf:'center',padding:24,borderWidth:StyleSheet.hairlineWidth,borderRadius:24,gap:18},title:{fontSize:24,fontWeight:'700',fontFamily:brand.serif},input:{minHeight:52,borderWidth:1,borderRadius:16,paddingHorizontal:16,paddingVertical:13,fontSize:16},primary:{minHeight:52,borderRadius:26,alignItems:'center',justifyContent:'center'},link:{minHeight:44,justifyContent:'center'},code:{fontSize:16,lineHeight:25,padding:16,borderRadius:12}});
