import {StyleSheet} from 'react-native';
export const styles=StyleSheet.create({
 reader:{flex:1},readingHeading:{height:34,paddingHorizontal:24,justifyContent:'center'},readingBody:{flex:1,marginHorizontal:24,overflow:'hidden'},readingFooter:{height:60,paddingHorizontal:24,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},readingProgress:{minHeight:44,justifyContent:'center',flex:1},listenBubble:{width:48,height:48,borderRadius:24,alignItems:'center',justifyContent:'center'},readerTopToolbar:{position:'absolute',top:0,left:0,right:0,minHeight:56,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:StyleSheet.hairlineWidth},readerBottomToolbar:{position:'absolute',bottom:0,left:0,right:0,paddingHorizontal:22,paddingBottom:6,borderTopWidth:StyleSheet.hairlineWidth},readerPageNavigation:{height:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},readerTools:{height:64,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},readerTool:{minHeight:52,minWidth:48,alignItems:'center',justifyContent:'center',gap:3},readerError:{position:'absolute',left:20,right:20,padding:14,borderWidth:1,borderRadius:14,shadowOpacity:0.08,shadowRadius:6,shadowOffset:{width:0,height:3},elevation:3,gap:10},
readerErrorHeader:{flexDirection:'row',alignItems:'flex-start',gap:10},
readerErrorBadge:{width:24,height:24,borderRadius:12,alignItems:'center',justifyContent:'center',marginTop:2},
readerErrorBadgeText:{fontSize:14,fontWeight:'700',lineHeight:16},
readerErrorTitle:{fontSize:15,fontWeight:'600',lineHeight:20},
readerErrorHint:{fontSize:12,lineHeight:17,marginTop:2},
readerErrorDismiss:{width:28,height:28,borderRadius:14,alignItems:'center',justifyContent:'center'},
readerErrorDetail:{fontSize:11,lineHeight:15,opacity:0.85},
readerErrorAction:{height:36,borderRadius:18,alignItems:'center',justifyContent:'center',paddingHorizontal:16},
readerErrorActionText:{fontSize:14,fontWeight:'600'},themeCard:{width:'22%',minHeight:88,borderRadius:15,alignItems:'center',justifyContent:'center',paddingVertical:12},settingsPlayback:{flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderRadius:16,padding:15},page:{flex:1},header:{height:60,flexDirection:'row',alignItems:'center',paddingHorizontal:20,borderBottomWidth:1,gap:14},headerTitle:{fontSize:18,fontWeight:'600',flex:1,textAlign:'center'},iconButton:{minHeight:48,minWidth:48,justifyContent:'center',alignItems:'center'},button:{minHeight:44,paddingHorizontal:17,paddingVertical:11,borderRadius:13,borderWidth:1,alignItems:'center',justifyContent:'center'},notice:{padding:14,fontSize:14,lineHeight:22},login:{flexGrow:1,justifyContent:'center',padding:30},shelfIntro:{padding:24,paddingBottom:16},actions:{flexDirection:'row',gap:12,paddingHorizontal:18},cover:{height:208,borderRadius:12,padding:20,justifyContent:'space-between'},coverTitle:{fontSize:25,fontWeight:'500',color:'#F4EEDA',lineHeight:36},coverAuthor:{color:'#E5DCC1',fontSize:13},coverRule:{height:2,width:35,backgroundColor:'#C5BDA5',opacity:.65},chapterBar:{flexDirection:'row',alignItems:'center',paddingHorizontal:24,paddingVertical:17},paper:{flex:1,marginHorizontal:16,borderRadius:18,borderWidth:1,padding:24,paddingBottom:16},pageFooter:{flexDirection:'row',justifyContent:'space-between',borderTopWidth:1,paddingTop:14,marginTop:14},pageControls:{height:55,paddingHorizontal:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},player:{height:94,borderTopWidth:1,paddingHorizontal:24,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},play:{width:64,height:64,borderRadius:32,alignItems:'center',justifyContent:'center'},modalHeader:{flexDirection:'row',padding:20,justifyContent:'space-between',alignItems:'center'},tocRow:{paddingHorizontal:24,paddingVertical:18,borderBottomWidth:1},label:{fontSize:14,fontWeight:'600'},chips:{flexDirection:'row',flexWrap:'wrap',gap:9},input:{borderWidth:1,borderRadius:12,padding:14,fontSize:16,minHeight:48},
});

