"use client";
import {createLibrary} from "@/lib/local-library";
import {createProgressSaver} from "@/lib/progress-saver";
import Link from "next/link";
import { NovelReader, type PageLayout } from "@/components/novel-reader";
import { VoicePicker } from "@/components/voice-picker";
import { voiceOptions } from "@/lib/voices";
import { ChapterNavigation } from "@/components/chapter-navigation";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, Headphones, Plus, Play, Pause, ChevronLeft, ChevronRight, Settings2, Library, List, Volume2, Moon, Upload, FileText, Check, Loader2, Trash2, Plug, ArrowUpRight, RefreshCw, X, Sun, Type, Cloud, SkipBack, SkipForward } from "lucide-react";
import { Sidebar, SidebarProvider, SidebarContent, SidebarTrigger } from "@/components/ui/sidebar";
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogHeader } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogAction, AlertDialogCancel, AlertDialogFooter } from "@/components/ui/alert-dialog";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { Toaster, toast } from "sonner";
import { samples, sentences, type Book } from "@/lib/books";
import { defaultConfig, speechBlob, type VoiceConfig } from "@/lib/speech";
import { SpeechBuffer } from "@/lib/speech-buffer";

type Prefs={preload:number;speed:number;fontSize:number;highlight:boolean;autoPage:boolean;theme:"light"|"dark"};
type ImportJob={id:string;name:string;status:"loading"|"success"|"error";error?:string;book?:Book;file?:File};
const defaultPrefs:Prefs={preload:4,speed:1,fontSize:20,highlight:true,autoPage:true,theme:"light"};
async function request<T=unknown>(url:string,init?:RequestInit){const r=await fetch(url,init);const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error||"请求失败，请重试。");return data as T;}
function Pick({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>}
function Cover({book,large=false}:{book:Book;large?:boolean}){return <div aria-hidden="true" className={`${large?"book-cover":"mini-cover"} cover-${book.color||"green"}`}><span>{book.title.slice(0,12)}</span>{large&&<small>{book.author}</small>}</div>}
function ReadingSettings({prefs,setPrefs,config,setApi,voices,onVoice,onConfig,timer,setTimer}:{prefs:Prefs;setPrefs:(p:Prefs)=>void;config:VoiceConfig;setApi:()=>void;voices:SpeechSynthesisVoice[];onVoice:(s:string)=>void;onConfig:(c:VoiceConfig)=>void;timer:number;setTimer:(n:number)=>void}){
 return <><div className="panel-heading"><Headphones size={19}/><h2>听读设置</h2></div><button className="voice-card" onClick={setApi}><div className="voice-avatar"><Volume2/></div><div><b>{config.provider==="browser"?"系统语音":config.provider==="glm"?"GLM-TTS · 智谱语音":"MiniMax · 中国区语音"}</b><small>{config.provider==="browser"?"浏览器内置 · 随时开听":`${config.voice} · AI 合成`}</small></div><ChevronRight size={14}/></button>{config.provider==="browser"&&<Pick value={config.browserVoice} label="系统音色" onChange={onVoice} items={[{value:"auto",label:"自动匹配文本语言"},...voices.map(v=>({value:v.voiceURI,label:`${v.name} · ${v.lang}`}))]}/>}{config.provider!=="browser"&&<VoicePicker key={config.provider} config={config} onChange={onConfig} compact/>}<div className="setting-title">朗读速度 <b>{prefs.speed.toFixed(1)} ×</b></div><Slider aria-label="朗读速度" min={.5} max={2} step={.1} value={[prefs.speed]} onValueChange={v=>setPrefs({...prefs,speed:v[0]})}/><div className="range-labels"><span>0.5 ×</span><span>1.0 ×</span><span>2.0 ×</span></div><div className="settings-divider"/>{config.provider!=="browser"&&<><div className="setting-title">语音预合成</div><Pick label="预合成语音数量" value={String(prefs.preload)} onChange={v=>setPrefs({...prefs,preload:Number(v)})} items={[{value:"0",label:"关闭"},{value:"2",label:"提前 2 句"},{value:"4",label:"提前 4 句 · 推荐"},{value:"6",label:"提前 6 句 · 网络较慢"}]}/><small className="buffer-hint">边听边准备后续语音，减少句间等待。提前生成的内容也会按服务商规则计费。</small></>}<label className="setting-title"><span>自动翻页</span><Switch aria-label="自动翻页" checked={prefs.autoPage} onCheckedChange={autoPage=>setPrefs({...prefs,autoPage})}/></label><label className="setting-title"><span>句子高亮</span><Switch aria-label="句子高亮" checked={prefs.highlight} onCheckedChange={highlight=>setPrefs({...prefs,highlight})}/></label><div className="settings-divider"/><div className="setting-title"><span>文字大小</span><b>{prefs.fontSize}</b></div><div className="font-control"><Type size={15}/><Slider aria-label="文字大小" min={16} max={28} step={1} value={[prefs.fontSize]} onValueChange={v=>setPrefs({...prefs,fontSize:v[0]})}/><Type size={21}/></div><div className="setting-title">阅读主题</div><div className="theme-buttons"><button className={prefs.theme==="light"?"selected":""} onClick={()=>setPrefs({...prefs,theme:"light"})}><Sun size={16}/> 日间</button><button className={prefs.theme==="dark"?"selected":""} onClick={()=>setPrefs({...prefs,theme:"dark"})}><Moon size={16}/> 夜间</button></div><div className="setting-title"><span className="inline-label"><Moon size={15}/> 定时关闭</span></div><Pick label="定时关闭" value={String(timer)} onChange={v=>setTimer(Number(v))} items={[{value:"0",label:"不设置"},{value:"15",label:"15 分钟后"},{value:"30",label:"30 分钟后"},{value:"60",label:"60 分钟后"}]}/><button className="api-link" onClick={setApi}><Plug size={16}/> 接入语音 API <ArrowUpRight size={15}/></button><div className="quiet-card"><BookOpen size={22}/><p>读到哪里，听到哪里</p><small>跟随声音，慢慢读。<br/>把翻页交给听页。</small></div></>
}
export default function Home({userId}:{userId:string}){
 const library=useMemo(()=>createLibrary(userId),[userId]);const request=library.request;
 useEffect(()=>{const sync=()=>{void library.flush()};window.addEventListener("online",sync);const t=setInterval(sync,30000);return()=>{window.removeEventListener("online",sync);clearInterval(t)}},[library]);
 const [books,setBooks]=useState<Book[]>(samples),[book,setBook]=useState<Book>(samples[0]);const [chapter,setChapter]=useState(0),[index,setIndex]=useState(0),[page,setPage]=useState(0);const [prefs,setPrefs]=useState<Prefs>(defaultPrefs),[config,setConfig]=useState<VoiceConfig>(defaultConfig),[draft,setDraft]=useState<VoiceConfig>(defaultConfig);const [voices,setVoices]=useState<SpeechSynthesisVoice[]>([]);
 const [active,setActive]=useState(false),[paused,setPaused]=useState(false),[loadingAudio,setLoadingAudio]=useState(false),[audioError,setAudioError]=useState("");const pausedRef=useRef(false),audioRef=useRef<HTMLAudioElement|null>(null),utteranceRef=useRef<SpeechSynthesisUtterance|null>(null),generation=useRef(0);const [volume,setVolume]=useState(.8),volumeRef=useRef(.8);const [timer,setTimer]=useState(0),[deadline,setDeadline]=useState(0);
 const [tocOpen,setTocOpen]=useState(false);const [glmStatus,setGlmStatus]=useState<{configured:boolean;model:string;voice:string}|null>(null);
 const [libraryOpen,setLibraryOpen]=useState(false),[importOpen,setImportOpen]=useState(false),[apiOpen,setApiOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false);const [jobs,setJobs]=useState<ImportJob[]>([]),[paste,setPaste]=useState(""),[pasteTitle,setPasteTitle]=useState("");const [dragging,setDragging]=useState(false),[testBusy,setTestBusy]=useState(false),[deleteBook,setDeleteBook]=useState<Book|null>(null),[opening,setOpening]=useState("");const [libraryError,setLibraryError]=useState(""),[libraryLoading,setLibraryLoading]=useState(true),[saveState,setSaveState]=useState("本机阅读 · 手动备份与还原");const ready=useRef(false),changed=useRef(false),selection=useRef(0),fileRef=useRef<HTMLInputElement>(null),paperRef=useRef<HTMLElement>(null),testRef=useRef<{abort:AbortController;audio?:HTMLAudioElement;url?:string}|null>(null);
 const lines=useMemo(()=>sentences(book.chapters[chapter]?.text||""),[book,chapter]);
 const [pages,setPages]=useState<PageLayout>([{start:0,end:0}]),[spokenOffset,setSpokenOffset]=useState(0),[seekToken,setSeekToken]=useState(0);
 const [bufferVersion,setBufferVersion]=useState(0);
 const speechBuffer=useMemo(()=>new SpeechBuffer((text,signal)=>speechBlob(text,config,signal),()=>setBufferVersion(v=>v+1)),[config]);
 const speedRef=useRef(prefs.speed);const browserSpeed=config.provider==="browser"?prefs.speed:0;
 const upcoming=useMemo(()=>{const out:string[]=[];for(let c=chapter;c<book.chapters.length&&out.length<=prefs.preload;c++){const chapterLines=c===chapter?lines:sentences(book.chapters[c].text);for(let n=c===chapter?index:0;n<chapterLines.length&&out.length<=prefs.preload;n++)out.push(chapterLines[n]);}return out;},[book,chapter,index,lines,prefs.preload]);
 const buffered=speechBuffer.ready(upcoming.slice(1));void bufferVersion;
 useEffect(()=>()=>speechBuffer.clear(),[speechBuffer]);
 useEffect(()=>{if(active&&config.provider!=="browser")speechBuffer.prepare(upcoming,paused);else speechBuffer.clear();},[active,config.provider,speechBuffer,upcoming,paused]);
 useEffect(()=>{speedRef.current=prefs.speed;if(audioRef.current)audioRef.current.playbackRate=prefs.speed;},[prefs.speed]);
 const onLayout=useCallback((next:PageLayout)=>setPages(next),[]);
 const currentPage=Math.max(0,pages.findIndex(p=>index>=p.start&&index<p.end));const progress=Math.round(((index+1)/Math.max(1,lines.length))*100);
 const stop=useCallback(()=>{setActive(false);setPaused(false);pausedRef.current=false;setLoadingAudio(false);generation.current++;window.speechSynthesis?.cancel();audioRef.current?.pause();speechBuffer.clear();},[speechBuffer]);
 const refreshLibrary=useCallback(async()=>{setLibraryLoading(true);setLibraryError("");try{const data=await request<{books:Book[]}>("/api/books");setBooks([...samples,...data.books]);}catch(e){setLibraryError((e as Error).message)}finally{setLibraryLoading(false)}},[]);
 useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem("tingye-prefs-v1")||"null");if(stored)setPrefs({...defaultPrefs,...stored,preload:[0,2,4,6].includes(stored.preload)?stored.preload:4,speed:Math.max(.5,Math.min(2,Number(stored.speed)||1)),fontSize:Math.max(16,Math.min(28,Number(stored.fontSize)||20))});}catch{}ready.current=true;void refreshLibrary();request<{glm:{configured:boolean;model:string;voice:string}}>("/api/tts").then(({glm})=>{setGlmStatus(glm);setConfig(c=>c.provider==="glm"?{...c,model:glm.model,voice:glm.voice}:c)}).catch(()=>{});const token=selection.current;request<Book>("/api/books?id="+samples[0].id).then(b=>{if(selection.current===token&&!changed.current){setChapter(b.chapter||0);setIndex(b.position||0);}}).catch(()=>{});const update=()=>setVoices(window.speechSynthesis?.getVoices()||[]);update();window.speechSynthesis?.addEventListener("voiceschanged",update);return()=>{window.speechSynthesis?.removeEventListener("voiceschanged",update);window.speechSynthesis?.cancel();testRef.current?.abort.abort();testRef.current?.audio?.pause();if(testRef.current?.url)URL.revokeObjectURL(testRef.current.url);};},[refreshLibrary]);
 useEffect(()=>{document.documentElement.dataset.theme=prefs.theme;if(ready.current){try{localStorage.setItem("tingye-prefs-v1",JSON.stringify(prefs))}catch{}}},[prefs]);

 useEffect(()=>{volumeRef.current=volume;if(audioRef.current)audioRef.current.volume=volume;if(utteranceRef.current)utteranceRef.current.volume=volume;},[volume]);
 const progressSaver=useMemo(()=>createProgressSaver(value=>request("/api/books",{method:"PATCH",body:JSON.stringify(value)}),state=>setSaveState(state==='saving'?'正在保存…':state==='saved'?'进度已存本机':'本机保存失败')),[library]);
 useEffect(()=>{if(changed.current)progressSaver.schedule({id:book.id,chapter,position:index,updatedAt:Date.now()});},[book.id,chapter,index,progressSaver]);
 useEffect(()=>{
  const save=()=>{void progressSaver.flush().catch(()=>{});};
  const hidden=()=>{if(document.visibilityState==='hidden')save();};
  document.addEventListener('visibilitychange',hidden);window.addEventListener('pagehide',save);
  return()=>{document.removeEventListener('visibilitychange',hidden);window.removeEventListener('pagehide',save);save();};
 },[progressSaver]);
 useEffect(()=>{if(!deadline)return;const remaining=deadline-Date.now();const t=setTimeout(()=>{stop();setTimer(0);setDeadline(0);toast("定时已到，休息一下吧。");},Math.max(0,remaining));return()=>clearTimeout(t)},[deadline,stop]);
 useEffect(()=>{
  if(!active||!lines[index])return;const token=++generation.current;const controller=new AbortController();let objectUrl="";let utterance:SpeechSynthesisUtterance|undefined;setAudioError("");setSpokenOffset(0);
  const valid=()=>generation.current===token&&!controller.signal.aborted;
  const done=()=>{if(!valid())return;changed.current=true;if(index+1<lines.length)setIndex(index+1);else if(chapter+1<book.chapters.length){setChapter(chapter+1);setIndex(0);setPage(0);}else{setActive(false);setPaused(false);pausedRef.current=false;toast.success("这本书听完了。");}};
  const failed=(message:string)=>{if(!valid())return;setAudioError(message);setActive(false);setPaused(false);pausedRef.current=false;setLoadingAudio(false);};
  if(config.provider==="browser"){
   if(!window.speechSynthesis){failed("当前浏览器不支持系统朗读，请接入语音 API。");return;}
   window.speechSynthesis.cancel();utterance=new SpeechSynthesisUtterance(lines[index]);utteranceRef.current=utterance;utterance.lang=/[\u4e00-\u9fff]/.test(lines[index])?"zh-CN":"en-US";const available=window.speechSynthesis.getVoices();const selected=config.browserVoice==="auto"?available.find(v=>v.lang.startsWith(utterance!.lang.slice(0,2))):available.find(v=>v.voiceURI===config.browserVoice);if(selected)utterance.voice=selected;utterance.rate=speedRef.current;utterance.volume=volumeRef.current;utterance.onboundary=e=>{if(valid())setSpokenOffset(e.charIndex)};utterance.onend=done;utterance.onerror=e=>{if(!["canceled","interrupted"].includes(e.error))failed("系统朗读不可用，请选择其他音色或接入语音 API。");};setLoadingAudio(false);window.speechSynthesis.speak(utterance);if(pausedRef.current)window.speechSynthesis.pause();
  }else{
   setLoadingAudio(true);
   speechBuffer.get(lines[index]).then(async blob=>{if(!valid())return;objectUrl=URL.createObjectURL(blob);const audio=audioRef.current||new Audio();audioRef.current=audio;audio.src=objectUrl;audio.volume=volumeRef.current;audio.playbackRate=speedRef.current;audio.ontimeupdate=()=>{if(valid()&&Number.isFinite(audio.duration)&&audio.duration>0)setSpokenOffset(Math.floor(lines[index].length*audio.currentTime/audio.duration))};audio.onended=done;audio.onerror=()=>failed("音频无法播放，请检查接口返回格式。");setLoadingAudio(false);if(!pausedRef.current)await audio.play();}).catch(e=>{if(generation.current===token){failed(controller.signal.aborted?"语音生成超时，请重试。":(e as Error).message);if(controller.signal.aborted){setAudioError("语音生成超时，请重试。");setActive(false);setLoadingAudio(false);}}});
  }
  return()=>{controller.abort();if(utterance){utterance.onboundary=null;utterance.onend=null;utterance.onerror=null;window.speechSynthesis?.cancel();}if(audioRef.current){audioRef.current.ontimeupdate=null;audioRef.current.onended=null;audioRef.current.onerror=null;audioRef.current.pause();}if(objectUrl)URL.revokeObjectURL(objectUrl);};
 },[active,book,chapter,index,config,browserSpeed,lines,speechBuffer,seekToken]);
 function unlockAudio(){if(config.provider==="browser"&&draft.provider==="browser")return;const a=audioRef.current;if(!a)return;if(!a.src||a.paused){a.src="/silence.wav";const silent=a.src;void a.play().then(()=>{if(a.src===silent)a.pause()}).catch(()=>{});}}
 function toggle(){changed.current=true;if(!active){unlockAudio();setAudioError("");pausedRef.current=false;setPaused(false);setActive(true);return;}const next=!pausedRef.current;pausedRef.current=next;setPaused(next);if(config.provider==="browser"){if(next)window.speechSynthesis?.pause();else window.speechSynthesis?.resume();}else if(next)audioRef.current?.pause();else if(!loadingAudio)audioRef.current?.play().catch(()=>{stop();setAudioError("浏览器阻止了播放，请再次点击播放。");});}
 function seek(ci:number,i:number){generation.current++;setSpokenOffset(0);setSeekToken(t=>t+1);changed.current=true;const max=sentences(book.chapters[ci].text).length-1;setChapter(ci);const nextIndex=Math.max(0,Math.min(max,i));setIndex(nextIndex);setPage(ci===chapter?Math.max(0,pages.findIndex(p=>nextIndex>=p.start&&nextIndex<p.end)):0);}
 function step(delta:number){if(index+delta<0&&chapter>0)seek(chapter-1,sentences(book.chapters[chapter-1].text).length-1);else if(index+delta>=lines.length&&chapter<book.chapters.length-1)seek(chapter+1,0);else seek(chapter,index+delta);}
 function turnPage(delta:number){const target=page+delta;if(target<0&&chapter>0){seek(chapter-1,0);return;}if(target>=pages.length&&chapter<book.chapters.length-1){seek(chapter+1,0);return;}if(pages[target]){stop();setSpokenOffset(0);changed.current=true;setIndex(pages[target].start);setPage(target);}}
 async function openBook(b:Book){stop();const token=++selection.current;setOpening(b.id);try{await progressSaver.flush();const full=await request<Book>("/api/books?id="+encodeURIComponent(b.id));if(selection.current!==token)return;setBook(full);setChapter(full.chapter||0);setIndex(full.position||0);setPage(0);changed.current=false;setLibraryOpen(false);}catch(e){toast.error((e as Error).message);}finally{if(selection.current===token)setOpening("");}}
 async function importOne(file?:File,retry?:ImportJob){const id=retry?.id||crypto.randomUUID();let parsed=retry?.book;const name=retry?.name||file?.name||pasteTitle.trim()||"粘贴的文本";setJobs(j=>retry?j.map(x=>x.id===id?{...x,status:"loading",error:undefined}:x):[...j,{id,name,status:"loading",file}]);try{if(!parsed){const parser=await import("@/lib/import-book");parsed=file?await parser.parseBook(file):{id:crypto.randomUUID(),title:name.slice(0,200),author:"我的文本",format:"TXT",chapters:parser.textChapters(paste),color:"green"};if(!parsed.chapters.length)throw new Error("请先输入可朗读的正文。");}await request("/api/books",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(parsed)});const saved=parsed;setBooks(b=>[...b.filter(x=>x.id!==saved.id),saved]);setJobs(j=>j.map(x=>x.id===id?{...x,status:"success",book:saved}:x));toast.success(`《${parsed.title}》已加入书架`);}catch(e){setJobs(j=>j.map(x=>x.id===id?{...x,status:"error",error:(e as Error).message,book:parsed}:x));}}
 async function filesImport(files:FileList|File[]|null){if(!files)return;for(const file of Array.from(files))await importOne(file);if(fileRef.current)fileRef.current.value="";}
 function showApi(){stop();setSettingsOpen(false);setDraft({...config});setApiOpen(true);}
 function stopTest(){testRef.current?.abort.abort();testRef.current?.audio?.pause();if(testRef.current?.url)URL.revokeObjectURL(testRef.current.url);testRef.current=null;window.speechSynthesis?.cancel();setTestBusy(false);}
 async function testVoice(){stopTest();stop();unlockAudio();setTestBusy(true);if(draft.provider==="browser"){if(!window.speechSynthesis){toast.error("此浏览器不支持系统语音。");setTestBusy(false);return;}const u=new SpeechSynthesisUtterance("你好，欢迎来到听页。让每一页，都有声音。");u.lang="zh-CN";u.voice=voices.find(v=>v.voiceURI===draft.browserVoice)||voices.find(v=>v.lang.startsWith("zh"))||null;u.onend=()=>{setTestBusy(false);toast.success("试听结束")};u.onerror=()=>{setTestBusy(false);toast.error("系统语音暂不可用，请选择其他音色。")};window.speechSynthesis.speak(u);return;}const abort=new AbortController();const current={abort,audio:undefined as HTMLAudioElement|undefined,url:undefined as string|undefined};testRef.current=current;const timeout=setTimeout(()=>abort.abort(),55000);try{const blob=await speechBlob("你好，欢迎来到听页。让每一页，都有声音。",draft,abort.signal);if(abort.signal.aborted)return;current.url=URL.createObjectURL(blob);current.audio=audioRef.current||new Audio();current.audio.src=current.url;current.audio.onended=()=>{stopTest();toast.success("连接成功，试听结束。")};current.audio.onerror=()=>{stopTest();toast.error("返回的音频无法播放。")};await current.audio.play();}catch(e){if(testRef.current===current){stopTest();toast.error(abort.signal.aborted?"试听超时，请重试。":(e as Error).message)}}finally{clearTimeout(timeout)}}
 function preset(provider:VoiceConfig["provider"]){stopTest();setDraft(d=>({...d,provider,key:"",extraVoices:[],model:provider==='minimax'?'speech-2.8-hd':'glm-tts',voice:provider==='minimax'?'male-qn-qingse':'tongtong'}));}
 const controls={prefs,setPrefs,config,setApi:showApi,voices,onVoice:(browserVoice:string)=>setConfig({...config,browserVoice}),onConfig:setConfig,timer,setTimer:(n:number)=>{setTimer(n);setDeadline(n?Date.now()+n*60000:0);}};
 useEffect(()=>{function key(e:KeyboardEvent){const target=e.target as HTMLElement;if(target.closest("input,textarea,select,[role='slider'],[role='dialog'],[role='combobox']")||libraryOpen||importOpen||apiOpen||settingsOpen||tocOpen||deleteBook)return;if(e.code==="Space"&&target===document.body){e.preventDefault();toggle();}if(e.key==="ArrowRight"&&target===document.body){e.preventDefault();turnPage(1)}if(e.key==="ArrowLeft"&&target===document.body){e.preventDefault();turnPage(-1)}}window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)});
 return <SidebarProvider><audio ref={audioRef} preload="auto" playsInline aria-hidden="true" className="sr-only"/><Toaster position="top-center" richColors/><Sidebar className="library-sidebar"><SidebarContent><Link className="brand" href="/" aria-label="听页首页"><span className="brand-icon"><Headphones/></span><b>听页<span>TINGYE</span></b></Link><div className="side-inner"><button className="side-link" onClick={()=>setLibraryOpen(true)}><Library size={19}/> 我的书架 <span>{books.length}</span></button><div className="side-title">正在阅读</div><button className="book-mini" onClick={()=>setLibraryOpen(true)}><Cover book={book}/><div><b>{book.title}</b><small>{book.author} · {book.format}</small></div></button><div className="side-title"><List size={16}/> 章节目录 <span className="chapter-count">{book.chapters.length}</span></div><nav aria-label="章节目录">{book.chapters.map((c,i)=><button className={chapter===i?"chapter active":"chapter"} aria-current={chapter===i?"location":undefined} key={i} onClick={()=>seek(i,0)}><span>{String(i+1).padStart(2,"0")}</span><span className="chapter-name">{c.title}</span>{chapter===i&&active&&!paused&&<span className="equalizer">▥</span>}</button>)}</nav></div><div className="side-bottom"><Headphones size={18}/><span>让每一页，都有声音。</span></div></SidebarContent></Sidebar><main className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><button onClick={()=>setLibraryOpen(true)}>我的书架</button><ChevronRight size={14}/><b>{book.title}</b></div><div className="top-actions"><button className="secondary-button" onClick={async()=>{stop();try{await progressSaver.flush();await library.flush();const r=await fetch("/api/auth",{method:"DELETE"});if(r.ok)window.location.assign("/login");else toast.error("退出失败，请重试。")}catch(e){toast.error((e as Error).message)}}}>退出账号</button><span className="local-label"><Cloud size={14}/>{saveState}</span><button className="primary" onClick={()=>setImportOpen(true)}><Plus size={17}/> 导入书籍</button></div></header>
 <div className="reading-layout"><section className="reading-column"><div className="reader-toolbar"><span><BookOpen size={16}/> 沉浸阅读 <span className="toolbar-dot">/</span> {book.format}</span><div className="toolbar-actions"><button className="toc-trigger" onClick={()=>setTocOpen(true)}><List size={17}/>目录</button><button className="icon-button" onClick={()=>setPrefs({...prefs,theme:prefs.theme==="dark"?"light":"dark"})} aria-label="切换日间或夜间模式">{prefs.theme==="dark"?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button" onClick={()=>setSettingsOpen(true)} aria-label="阅读与听书设置"><Settings2 size={19}/></button></div></div>{audioError&&<div className="error-banner" role="alert"><span>{audioError}</span><button onClick={toggle}>重试</button><button onClick={showApi}>语音设置</button></div>}<article className="paper" ref={paperRef}><div className="book-label novel-book-title">{book.title} · {book.author}</div><NovelReader key={book.id+"-"+chapter} text={book.chapters[chapter]?.text||""} title={book.chapters[chapter]?.title||book.title} fontSize={prefs.fontSize} index={index} offset={spokenOffset} page={Math.min(page,pages.length-1)} follow={active&&!paused&&prefs.autoPage} seekToken={seekToken} highlight={prefs.highlight} onLayout={onLayout} onPage={setPage} onSentence={n=>{if(!active)unlockAudio();generation.current++;setSeekToken(t=>t+1);changed.current=true;setIndex(n);setSpokenOffset(0);pausedRef.current=false;setPaused(false);setActive(true);}}/><div className="page-footer"><span>点击任意句子，从这里开始听</span><span>{Math.min(page+1,pages.length)} <span className="muted">/ {pages.length}</span></span></div></article><div className="pagination-row"><button disabled={page===0&&chapter===0} onClick={()=>turnPage(-1)}><ChevronLeft size={16}/> 上一页</button>{active&&!prefs.autoPage&&page!==currentPage?<button onClick={()=>setPage(currentPage)}>回到朗读位置</button>:<span>{active?(paused?"声音暂停，文字停留":"文字与声音，一起向前") : "留一点时间，给阅读"}</span>}<button disabled={page===pages.length-1&&chapter===book.chapters.length-1} onClick={()=>turnPage(1)}>下一页 <ChevronRight size={16}/></button></div>{book.sample&&<p className="sample-note">内置公版作品节选 · 可从书架切换，或导入自己的完整书籍</p>}</section><aside className="controls-panel"><ReadingSettings {...controls}/></aside></div>
 <footer className="player"><nav className="mobile-reader-nav" aria-label="听读导航"><button onClick={()=>setLibraryOpen(true)}><Library size={18}/>书架</button><button onClick={()=>setTocOpen(true)}><List size={18}/>目录</button><button onClick={()=>setSettingsOpen(true)}><Settings2 size={18}/>设置</button></nav><div className="player-progress"><Slider aria-label="章节朗读进度" min={0} max={Math.max(1,lines.length-1)} step={1} value={[index]} onValueChange={v=>seek(chapter,v[0])}/></div><button className="now-playing" onClick={()=>setLibraryOpen(true)}><Cover book={book}/><div><b>{book.title}</b><small>{book.chapters[chapter]?.title}</small></div></button><div className="player-middle"><div className="play-center"><button className="skip-chapter" aria-label="上一章" disabled={chapter===0} onClick={()=>seek(chapter-1,0)}><SkipBack size={17}/></button><button aria-label="上一句" disabled={index===0&&chapter===0} onClick={()=>step(-1)}><ChevronLeft size={22}/></button><button className="play-button" onClick={toggle} aria-label={active&&!paused?"暂停朗读":"开始朗读"}>{loadingAudio&&!paused?<Loader2 className="animate-spin"/>:active&&!paused?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><button aria-label="下一句" disabled={index===lines.length-1&&chapter===book.chapters.length-1} onClick={()=>step(1)}><ChevronRight size={22}/></button><button className="skip-chapter" aria-label="下一章" disabled={chapter===book.chapters.length-1} onClick={()=>seek(chapter+1,0)}><SkipForward size={17}/></button></div><div className="play-status" aria-live="polite">{paused?"已暂停":loadingAudio?"正在准备语音…":active?(config.provider!=="browser"&&prefs.preload>0?`正在朗读 · 已预合成 ${buffered} 句`:"正在朗读"):"准备好，听一会儿"}<span>第 {index+1} / {lines.length} 句 · {progress}%</span></div></div><div className="player-right"><button onClick={()=>setSettingsOpen(true)} aria-label="设置朗读速度">{prefs.speed.toFixed(1)} ×</button><Volume2 size={18}/><Slider aria-label="音量" min={0} max={1} step={.05} value={[volume]} onValueChange={v=>setVolume(v[0])} className="volume-slider"/><button onClick={()=>setSettingsOpen(true)} aria-label="定时关闭" className={timer?"timer-active":""}><Moon size={18}/>{timer>0&&<small>{timer}m</small>}</button></div></footer>
 <ChapterNavigation key={`${book.id}-${tocOpen}`} book={book} current={chapter} open={tocOpen} onOpenChange={setTocOpen} onJump={i=>{seek(i,0);requestAnimationFrame(()=>paperRef.current?.scrollIntoView({block:"start",behavior:"smooth"}))}}/>
 <Dialog open={libraryOpen} onOpenChange={setLibraryOpen}><DialogContent className="library-dialog"><DialogHeader><DialogTitle>我的书架</DialogTitle><DialogDescription>把喜欢的文字，变成耳边的声音。</DialogDescription></DialogHeader><div className="library-top"><span>{books.length} 本书 · 正文优先保存在本机</span><button className="primary" onClick={()=>{setLibraryOpen(false);setImportOpen(true)}}><Plus size={16}/> 导入书籍</button></div>{libraryLoading&&<p className="inline-label"><Loader2 size={16} className="animate-spin"/> 正在加载书架…</p>}{libraryError&&<div className="error-banner"><span>{libraryError}</span>{libraryError.includes("登录")&&<a href="/login" target="_top">登录</a>}<button onClick={refreshLibrary}><RefreshCw size={15}/> 重试</button></div>}<div className="book-grid">{books.map(b=><div className="library-book" key={b.id}><button onClick={()=>openBook(b)} disabled={!!opening}><Cover book={b} large/><b>{b.title}</b><small>{b.author} · {b.format}</small><span className="read-link">{opening===b.id?"正在打开…":book.id===b.id?"继续听读":"开始听读"}<ChevronRight size={14}/></span></button>{!b.sample&&<button className="secondary-button" onClick={async()=>{try{toast("正在备份完整书籍和阅读位置…");await progressSaver.flush();await library.backup(b.id);toast.success("已备份，可在其他设备下载阅读。");await refreshLibrary();}catch(e){toast.error((e as Error).message)}}}>上传完整备份</button>}{!b.sample&&<button className="secondary-button" onClick={async()=>{if(!window.confirm("从云端还原将替换这本书的本机内容和阅读位置。继续？"))return;try{stop();await progressSaver.flush();changed.current=false;const restored=await library.restore(b.id);if(book.id===b.id){setBook(restored);setChapter(restored.chapter||0);setIndex(restored.position||0);setPage(0);}await refreshLibrary();toast.success("书籍和阅读位置已从云端还原。");}catch(e){toast.error((e as Error).message)}}}>从云端还原</button>}{!b.sample&&<button className="delete-book" aria-label={`删除 ${b.title}`} onClick={()=>setDeleteBook(b)}><Trash2 size={15}/></button>}</div>)}</div></DialogContent></Dialog>
 <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent className="import-dialog"><DialogHeader><DialogTitle>导入一本好书</DialogTitle><DialogDescription>支持多种文档格式，导入后即可开始听读。</DialogDescription></DialogHeader><Tabs defaultValue="file"><TabsList className="w-full"><TabsTrigger value="file"><Upload size={15}/> 本地文件</TabsTrigger><TabsTrigger value="text"><FileText size={15}/> 粘贴文本</TabsTrigger></TabsList><TabsContent value="file"><div className={`dropzone ${dragging?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);void filesImport(e.dataTransfer.files)}}><Upload size={30}/><h3>把书拖到这里</h3><p>或从设备中选择文件，可一次导入多本</p><button className="primary" onClick={()=>fileRef.current?.click()}>选择文件</button><input ref={fileRef} type="file" multiple accept=".txt,.epub,.pdf,.docx,.md,.markdown,.html,.htm" onChange={e=>void filesImport(e.target.files)} className="sr-only" aria-label="选择书籍文件"/><div className="file-types">TXT · EPUB · PDF · DOCX · MD · HTML</div></div><small className="import-hint">单本不超过 20 MB，正文不超过 400 万字。支持 UTF-8 / GB18030 文本。扫描版 PDF 需先做 OCR；EPUB 须无 DRM。</small></TabsContent><TabsContent value="text"><label className="form-field">书名<input value={pasteTitle} onChange={e=>setPasteTitle(e.target.value)} maxLength={200} placeholder="给这段文字起个名字"/></label><label className="form-field">正文<textarea value={paste} onChange={e=>setPaste(e.target.value)} maxLength={4000000} placeholder="粘贴文章或书籍内容…" rows={8}/></label><button className="primary" disabled={!paste.trim()||jobs.some(j=>j.status==="loading")} onClick={()=>void importOne()}>加入书架</button></TabsContent></Tabs><div className="import-jobs" aria-live="polite">{jobs.map(j=><div className="import-job" key={j.id}>{j.status==="loading"?<Loader2 className="animate-spin" size={17}/>:j.status==="success"?<Check size={17}/>:<X size={17}/>}<div><b>{j.name}</b><small>{j.error||(j.status==="loading"?"解析并保存中…":"已保存到本机书架")}</small></div>{j.status==="error"&&<button onClick={()=>void importOne(j.file,j)}>重试</button>}{j.status==="success"&&j.book&&<button onClick={()=>{setImportOpen(false);void openBook(j.book!)}}>阅读</button>}</div>)}</div></DialogContent></Dialog>
 <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent className="settings-dialog"><DialogHeader><DialogTitle>阅读与听书设置</DialogTitle><DialogDescription>找到舒服的声音和阅读节奏。</DialogDescription></DialogHeader><ReadingSettings {...controls}/></DialogContent></Dialog>
 <Dialog open={apiOpen} onOpenChange={v=>{if(!v)stopTest();setApiOpen(v)}}><DialogContent className="api-dialog"><DialogHeader><DialogTitle>语音引擎</DialogTitle><DialogDescription>选择本地语音、GLM 或 MiniMax。</DialogDescription></DialogHeader><label className="form-field">语音来源<Pick label="语音来源" value={draft.provider} onChange={v=>preset(v as VoiceConfig['provider'])} items={[{value:'browser',label:'本地语音'},{value:'glm',label:'GLM'},{value:'minimax',label:'MiniMax · 中国区'}]}/></label>{draft.provider==='browser'?<label className="form-field">本地音色<Pick label="试听音色" value={draft.browserVoice} onChange={browserVoice=>{stopTest();setDraft({...draft,browserVoice})}} items={[{value:'auto',label:'自动匹配文本语言'},...voices.map(v=>({value:v.voiceURI,label:v.name+' · '+v.lang}))]}/></label>:<div className="glm-config-card"><b>{draft.provider==='glm'?'GLM-TTS':'MiniMax Speech 2.8 HD'}</b><p>使用服务端密钥，无需在设备上填写。</p><VoicePicker key={draft.provider} config={draft} onChange={c=>{stopTest();setDraft(c)}}/><small>朗读文本会发送给所选语音服务商。</small></div>}<div className="dialog-actions"><button className="secondary-button" onClick={testBusy?stopTest:()=>void testVoice()}>{testBusy?'停止试听':'连接并试听'}</button><button className="primary" onClick={()=>{if(draft.provider!=='browser'&&!draft.voice.trim()){toast.error('请选择音色。');return;}stopTest();setConfig({...draft});setApiOpen(false);toast.success('语音配置已应用。');}}>应用设置</button></div></DialogContent></Dialog>
 <AlertDialog open={!!deleteBook} onOpenChange={v=>{if(!v)setDeleteBook(null)}}><AlertDialogContent><AlertDialogTitle>从书架移除《{deleteBook?.title}》？</AlertDialogTitle><AlertDialogDescription>将移除此设备的书籍、云端备份和同步进度。其他设备的本地文件不会自动删除。</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>保留</AlertDialogCancel><AlertDialogAction onClick={async()=>{const b=deleteBook;if(!b)return;try{await progressSaver.flush();await request("/api/books?id="+b.id,{method:"DELETE"});setBooks(list=>list.filter(x=>x.id!==b.id));if(book.id===b.id){stop();setBook(samples[0]);setChapter(0);setIndex(0);changed.current=false;}toast.success("已从书架移除")}catch(e){toast.error((e as Error).message)}}}>移除书籍</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main></SidebarProvider>
}
