import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import ts from 'typescript';
import JSZip from 'jszip';
await mkdir('.sites-runtime',{recursive:true});
const source=await readFile('lib/import-book.ts','utf8');
const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace('mammoth/mammoth.browser"','mammoth/mammoth.browser.js"');
await writeFile('.sites-runtime/import-parser-test.mjs',output);
const {parseBook}=await import('../.sites-runtime/import-parser-test.mjs');
const txt=await parseBook(new File(['第一章 归乡\n你好，世界。\n第二章 希望\n新的起点。'],'测试.txt'));
assert.equal(txt.chapters.length,2);assert.equal(txt.chapters[1].title,'第二章 希望');assert.equal(txt.chapters[0].text,'你好，世界。');
const md=await parseBook(new File(['# First chapter\nHello world!\n# Second chapter\nA second page.'],'test.md'));
assert.equal(md.chapters.length,2);assert.equal(md.format,'MD');
const zip=new JSZip();zip.file('[Content_Types].xml','<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');
zip.file('_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');
zip.file('word/document.xml','<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Hello from a Word book.</w:t></w:r></w:p></w:body></w:document>');
const docx=await parseBook(new File([await zip.generateAsync({type:'uint8array'})],'test.docx'));
assert.ok(docx.chapters[0].text.includes('Hello from a Word book.'));
await assert.rejects(()=>parseBook(new File([''],'empty.txt')),/没有可朗读/);
await assert.rejects(()=>parseBook(new File(['invalid'],'test.mobi')),/暂不支持/);
console.log('PASS: TXT chapter detection, Markdown chapter detection, real DOCX extraction, empty/unsupported import errors.');
