import { Book, Chapter } from "./books";
function clean(html:string){const doc=new DOMParser().parseFromString(html,"text/html");doc.querySelectorAll("script,style,nav,svg").forEach(n=>n.remove());doc.querySelectorAll("p,div,h1,h2,h3,br,li").forEach(n=>n.append("\n"));return doc.body.textContent?.replace(/[ \t]+/g," ").replace(/\n\s*\n/g,"\n\n").trim()||"";}
export function textChapters(text:string):Chapter[]{const result:Chapter[]=[];let title="正文",parts:string[]=[];for(const line of text.split(/\r?\n/)){if(/^(?:第[一二三四五六七八九十百千万零\d]+[章节回卷部]|chapter\s+[\divxlc]+\b|#{1,3}\s)/i.test(line.trim())&&line.trim().length<100){if(parts.join("").trim())result.push({title,text:parts.join("\n").trim()});title=line.replace(/^#+\s*/,"").trim();parts=[];}else parts.push(line)}if(parts.join("").trim())result.push({title,text:parts.join("\n").trim()});return result;}
export async function parseBook(file:File):Promise<Book>{
 if(file.size>20*1024*1024)throw new Error("单本文件请小于 20 MB。");
 const ext=file.name.split(".").pop()?.toLowerCase()||"";let title=file.name.replace(/\.[^.]+$/,""),author="我的导入",chapters:Chapter[]=[];const buffer=await file.arrayBuffer();
 if(["txt","md","markdown","html","htm"].includes(ext)){let text=new TextDecoder("utf-8").decode(buffer);if((text.match(/\uFFFD/g)||[]).length>3)text=new TextDecoder("gb18030").decode(buffer);chapters=textChapters(["html","htm"].includes(ext)?clean(text):text);}
 else if(ext==="docx"){const mammoth=await import("mammoth/mammoth.browser");const result=await mammoth.extractRawText({arrayBuffer:buffer});chapters=textChapters(result.value);}
 else if(ext==="epub"){
 const JSZip=(await import("jszip")).default;const zip=await JSZip.loadAsync(buffer);let expanded=0;for(const f of Object.values(zip.files)){expanded+=(f as unknown as {_data?:{uncompressedSize:number}})._data?.uncompressedSize||0;}if(expanded>60*1024*1024)throw new Error("解压后的书籍过大，请拆分后导入。");
 if(zip.file("META-INF/encryption.xml"))throw new Error("此 EPUB 含有加密内容，请导入无 DRM 的版本。");
 const container=await zip.file("META-INF/container.xml")?.async("string");if(!container)throw new Error("EPUB 文件缺少目录信息。");const xml=new DOMParser().parseFromString(container,"application/xml");const path=xml.getElementsByTagName("rootfile")[0]?.getAttribute("full-path");if(!path)throw new Error("无法找到 EPUB 正文。");const opfText=await zip.file(path)?.async("string");if(!opfText)throw new Error("EPUB 目录损坏。");const opf=new DOMParser().parseFromString(opfText,"application/xml");title=opf.getElementsByTagNameNS("*","title")[0]?.textContent||title;author=opf.getElementsByTagNameNS("*","creator")[0]?.textContent||author;const items=Array.from(opf.getElementsByTagName("item"));const refs=Array.from(opf.getElementsByTagName("itemref"));
 for(const ref of refs){if(ref.getAttribute("linear")==="no")continue;const item=items.find(x=>x.id===ref.getAttribute("idref"));const href=item?.getAttribute("href");if(!href)continue;const resolved=decodeURIComponent(new URL(href,"https://epub.invalid/"+path).pathname.slice(1));const html=await zip.file(resolved)?.async("string");if(!html)continue;const text=clean(html);if(!text.trim())continue;const doc=new DOMParser().parseFromString(html,"text/html");chapters.push({title:doc.querySelector("h1,h2,h3,title")?.textContent?.trim().slice(0,100)||`第 ${chapters.length+1} 节`,text});}
 }else if(ext==="pdf"){
 const pdfjs=await import("pdfjs-dist");pdfjs.GlobalWorkerOptions.workerSrc="/pdf.worker.min.mjs";const task=pdfjs.getDocument({data:new Uint8Array(buffer)});const pdf=await task.promise;
 try{if(pdf.numPages>1500)throw new Error("PDF 页数过多，请拆分到 1500 页以内。");for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const content=await page.getTextContent();const text=content.items.map(item=>"str" in item?item.str+(item.hasEOL?"\n":" "):"").join("");if(text.trim())chapters.push({title:`第 ${i} 页`,text});page.cleanup();}}finally{await task.destroy();}
 }else throw new Error("暂不支持该格式，请使用 TXT、EPUB、PDF、DOCX、Markdown 或 HTML。");
 if(!chapters.length)throw new Error(ext==="pdf"?"未提取到文字。扫描版 PDF 需先进行 OCR 文字识别。":"文件中没有可朗读的文字。");
 if(chapters.reduce((n,c)=>n+c.text.length,0)>4000000)throw new Error("正文超过 400 万字，请拆分后导入。");
 return {id:crypto.randomUUID(),title:title.slice(0,200),author:author.slice(0,100),format:ext.toUpperCase(),chapters,color:["green","blue","ochre"][Math.floor(Math.random()*3)],position:0,chapter:0};
}
