const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const moduleCode=file=>ts.transpileModule(fs.readFileSync('src/tingye/'+file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const books={exports:{}};vm.runInNewContext(moduleCode('books.ts'),{module:books,exports:books.exports});const mod={exports:{}};vm.runInNewContext(moduleCode('library.ts'),{module:mod,exports:mod.exports,TextEncoder,Date,URL,console,require:id=>require('./load-ts.cjs')('src/tingye/'+id.slice(2)+'.ts')});
const clone=v=>JSON.parse(JSON.stringify(v));
function storage(){let rows=[];const files=new Map();return {load:async()=>clone(rows),save:async value=>{rows=clone(value);},cover:async b=>b.cover?'file:///cache/'+b.id+'.png':undefined,read:async id=>files.get(id),write:async b=>files.set(b.id,clone(b)),remove:async id=>files.delete(id)};}
(async()=>{let online=false;const cloud=new Map(),uploads=new Map();const remote=async(path,options={})=>{if(!online)throw Error('offline');const b=options.body&&JSON.parse(options.body);if(options.method==='POST'){if(b.action==='backup-start')return {uploadId:b.id,url:'https://storage.test/'+b.id};if(b.action==='backup-complete'){cloud.get(b.uploadId).backedUp=true;return {ok:true};}cloud.set(b.id,{...cloud.get(b.id),...b});return {ok:true};}if(options.method==='PATCH'){assert.ok(Number.isSafeInteger(b.updatedAt));const existing=cloud.get(b.id);if(!existing.updatedAt||existing.updatedAt<b.updatedAt)Object.assign(existing,b);return {ok:true};}const id=new URL(path,'https://test').searchParams.get('id');if(options.method==='DELETE'){cloud.delete(id);return {ok:true};}return id?{...cloud.get(id),downloadUrl:uploads.has(id)?'https://storage.test/'+id:undefined}:{books:[...cloud.values()].map(b=>({...b,chapters:[]}))};};const transfer=async(url,options)=>{const id=url.split('/').pop();if(options?.method==='PUT'){uploads.set(id,JSON.parse(options.body));return {ok:true};}return {ok:true,json:async()=>clone(uploads.get(id))};};
const disk=storage(),a=mod.exports.createLibrary(disk,remote,transfer),book={id:'book_1',title:'测试',author:'作者',format:'TXT',chapters:[{title:'一',text:'保存到手机。网络断开也能阅读。',blocks:[{start:0,end:15,kind:'paragraph'}],marks:[{start:0,end:5,bold:true}]}]};
book.resources={r0:'data:image/png;base64,iVBORw0KGgo='};book.chapters[0].document={html:'<p><span data-pos="0">'+book.chapters[0].text+'</span></p><img src="tingye-resource:r0">',css:'p{line-height:1.8}',path:'OEBPS/one.xhtml'};await a.importBook(book);assert.equal((await disk.load())[0].resources,undefined);assert.equal((await a.open(book.id)).resources.r0,book.resources.r0);await a.progress(book,0,1);assert.equal((await a.open(book.id)).position,1);const restarted=mod.exports.createLibrary(disk,remote,transfer);assert.equal((await restarted.open(book.id)).chapters[0].text,book.chapters[0].text);assert.equal((await restarted.open(book.id)).position,1);
online=true;assert.equal(await restarted.flush(),true);assert.equal(cloud.get(book.id).position,1);await restarted.backup(book.id);assert.equal(uploads.get(book.id).cover,'r0');assert.equal(uploads.get(book.id).coverUri,undefined);const other=mod.exports.createLibrary(storage(),remote,transfer);await other.list(true);assert.equal((await other.open(book.id)).chapters[0].text,book.chapters[0].text);assert.equal((await other.open(book.id)).resources.r0,book.resources.r0);assert.equal((await other.list()).find(b=>b.id===book.id).coverUri,'file:///cache/'+book.id+'.png');assert.ok((await other.open(book.id)).chapters[0].document.html.includes('tingye-resource:r0'));assert.equal((await other.open(book.id)).chapters[0].marks[0].bold,true);assert.equal((await other.open(book.id)).chapters[0].blocks[0].end,15);
cloud.get(book.id).position=5;cloud.get(book.id).updatedAt=Date.now()+100;await restarted.list(true);assert.equal((await restarted.open(book.id)).position,5);
online=false;await restarted.remove(book.id);assert.ok(!(await restarted.list()).some(b=>b.id===book.id));online=true;await restarted.flush();assert.equal(cloud.has(book.id),false);const isolated=mod.exports.createLibrary(storage(),async()=>({books:[]}),transfer);assert.ok(!(await isolated.list()).some(b=>b.id===book.id));console.log('PASS: offline import/restart/progress, sync timestamps, private backup recovery, newer cloud progress, queued deletion and isolated storage.');})().catch(e=>{console.error(e);process.exitCode=1;});
