const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),JSZip=require('jszip');
const load=require('./load-ts.cjs'),{originalChapter,archiveResources,validateDocument,resourcePath}=load('src/tingye/original-document.ts');
const {originalPage}=load('src/tingye/original-page.ts'),{defaultTypography}=load('src/tingye/typesetting.ts'),{readingTheme}=load('src/tingye/themes.ts');
const out=path.resolve('.verify-android/original150');fs.mkdirSync(out,{recursive:true});
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6SAAAAABJRU5ErkJggg==';
(async()=>{
 const zip=new JSZip();zip.file('OEBPS/style/book.css','@import "more.css"; body{font-family:serif} h1{color:#286750;text-align:center} .verse{white-space:pre-wrap}.art{break-before:page;break-after:page} .caption{font-size:14px;color:#886638}');zip.file('OEBPS/style/more.css','p{margin:0 0 1em;text-indent:2em}');zip.file('OEBPS/images/page.png',Buffer.from(png,'base64'));zip.file('OEBPS/images/cover.svg','<svg xmlns="http://www.w3.org/2000/svg" width="300" height="400"><rect width="300" height="400" fill="#f5d197"/><text x="50" y="100">A BOOK</text><script>alert(1)</script></svg>');
 const content='<html><head><link rel="stylesheet" href="../style/book.css"></head><body><h1>山间来信</h1><p>清晨推开窗，山色映入眼帘。<strong>这是原书的加粗文字。</strong> 图片与文字在同一章。</p><figure class="art"><img src="../images/cover.svg" alt="原书插画"><figcaption class="caption">图一：山间的风，翻开书页。</figcaption></figure><p>'+('这一段很长，翻到下一页时，正文应始终可见，声音也应继续。'.repeat(180))+'</p><table><tr><th>季节</th><th>景色</th></tr><tr><td>春天</td><td>山花</td></tr></table><pre class="verse">山有木兮木有枝，\n心悦君兮君不知。</pre><p><a href="#ending">前往结尾</a></p><h2 id="ending">尾声</h2><p>读完最后一页。</p></body></html>';
 const assets=archiveResources(zip);
 const chapter=await originalChapter(content,'样书','OEBPS/text/one.xhtml',assets);
 assert.ok(chapter.document.html.includes('tingye-resource:'));assert.ok(chapter.document.html.includes('<table>'));assert.ok(chapter.document.html.includes('<strong>'));assert.ok(chapter.document.css.includes('text-indent:2em'));assert.ok(!chapter.document.css.includes('@import'));
 assert.ok(validateDocument(chapter.document,chapter.text));assert.equal(resourcePath('OEBPS/a.xhtml','https://example.com/a.png'),'');
 const malicious=await originalChapter('<script>bad()</script><p onclick="bad()">安全正文</p><img src="https://evil.test/a.png"><iframe src="file:///secret"></iframe><style>p{background:url(https://evil.test/tracker)}</style>','安全');assert.ok(!malicious.document.html.includes('onclick'));assert.ok(!malicious.document.html.includes('iframe'));assert.ok(!malicious.document.css.includes('evil.test'));assert.ok(!malicious.text.includes('bad'));
 const config={fontSize:22,typography:defaultTypography,colors:readingTheme('paper'),original:true};
 const fonts=`@font-face{font-family:ReaderSerif;src:url("file:///${path.resolve('assets/fonts/NotoSerifCJKsc-Regular.otf').replaceAll('\\','/')}")}`;
 fs.writeFileSync(path.join(out,'epub.html'),originalPage(chapter,config,0,fonts,assets.assets));fs.writeFileSync(path.join(out,'fixture.json'),JSON.stringify({chapter,config}));
 const imageOnly=await originalChapter('<figure><img src="../images/cover.svg"></figure>','封面','OEBPS/text/cover.xhtml',assets);assert.equal(imageOnly.text,'');assert.ok(imageOnly.document.html.includes('tingye-resource:'));fs.writeFileSync(path.join(out,'cover.html'),originalPage(imageOnly,config,0,'',assets.assets));
 const fixed=await originalChapter('<div style="position:absolute;top:40px;left:30px"><h1>原书固定页</h1><p>可以选择的文字</p><img src="../images/cover.svg"></div>','固定页','OEBPS/text/fixed.xhtml',assets,{width:600,height:800});fs.writeFileSync(path.join(out,'fixed.html'),originalPage(fixed,config,0,'',assets.assets));
 const {chromium}=require('playwright');const browser=await chromium.launch({channel:'msedge',headless:true,args:['--allow-file-access-from-files']});
 try{const page=await browser.newPage({viewport:{width:392,height:720},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.messages=[];window.ReactNativeWebView={postMessage:s=>window.messages.push(JSON.parse(s))};});
  await page.goto('file:///'+path.join(out,'epub.html').replaceAll('\\','/'));await page.waitForFunction(()=>window.messages.some(m=>m.type==='ready'));await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(250);
  const initial=await page.evaluate(()=>window.messages.filter(m=>m.type==='page').at(-1));assert.ok(initial.count>5);await page.screenshot({path:path.join(out,'01-epub.png')});
  assert.equal(await page.locator('img').evaluate(n=>n.complete&&n.naturalWidth>0&&n.getBoundingClientRect().width>20&&n.getBoundingClientRect().height>20),true);
  // Every character anchor must be visible on the selected page, including mid-paragraph page turns.
  for(let offset=0;offset<chapter.text.length;offset+=97){await page.evaluate(offset=>window.readerCommand({type:'seek',offset}),offset);const visible=await page.evaluate(offset=>{const nodes=[...document.querySelectorAll('[data-pos]')],span=nodes.find(n=>Number(n.dataset.pos)<=offset&&Number(n.dataset.pos)+n.textContent.length>offset)||nodes.find(n=>Number(n.dataset.pos)>=offset);if(!span)return true;const node=span.firstChild,r=document.createRange(),i=Math.max(0,Math.min(node.length-1,offset-Number(span.dataset.pos)));r.setStart(node,i);r.setEnd(node,i+1);const b=r.getBoundingClientRect();return b.width===0||(b.left>=-2&&b.left<innerWidth&&b.top>=-2&&b.bottom<=innerHeight+3);},offset);assert.ok(visible,'Hidden text at offset '+offset);}
  await page.evaluate(()=>window.readerCommand({type:'seek',offset:2000}));await page.screenshot({path:path.join(out,'02-cross-page.png')});
  await page.evaluate(c=>window.readerCommand({type:'config',value:{...c,original:false,fontSize:26,typography:{...c.typography,lineHeight:2.1}}}),config);await page.waitForTimeout(250);assert.ok(await page.locator('#ty-reader-book').isVisible());await page.screenshot({path:path.join(out,'03-settings-reflow.png')});
  await page.setViewportSize({width:360,height:610});await page.waitForTimeout(250);await page.evaluate(()=>window.readerCommand({type:'highlight',start:2100,end:2140}));assert.ok(await page.evaluate(()=>CSS.highlights.has('reading')));
  for(const name of ['cover','fixed']){await page.goto('file:///'+path.join(out,name+'.html').replaceAll('\\','/'));await page.waitForFunction(()=>window.messages.some(m=>m.type==='ready'));assert.ok(await page.locator('img').evaluate(n=>n.complete&&n.naturalWidth>0&&n.getBoundingClientRect().width>20&&n.getBoundingClientRect().height>20));await page.screenshot({path:path.join(out,name+'.png')});}
  await page.goto('file:///'+path.join(out,'cover.html').replaceAll('\\','/'));await page.waitForFunction(()=>window.messages.some(m=>m.type==='ready'));await page.locator('img').evaluate(n=>{n.style.height='3000px';n.style.width='300px';});await page.waitForTimeout(1800);const cover=await page.locator('img').evaluate(n=>n.getBoundingClientRect().toJSON());assert.ok(cover.left>=0&&cover.right<=360&&cover.top>=0&&cover.bottom<=610,'Oversized cover must not leave a blank leading page');assert.equal(await page.evaluate(()=>window.messages.filter(m=>m.type==='page').at(-1).count),1);
  const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 400] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];
  const stream='0.95 0.83 0.6 rg 30 50 240 220 re f BT /F1 20 Tf 30 350 Td (Original PDF page) Tj 0 -30 Td (Selectable text) Tj ET';objects.push('<< /Length '+stream.length+' >>\nstream\n'+stream+'\nendstream');let raw='%PDF-1.4\n',offsets=[0];objects.forEach((obj,i)=>{offsets.push(Buffer.byteLength(raw));raw+=(i+1)+' 0 obj\n'+obj+'\nendobj\n';});const xref=Buffer.byteLength(raw);raw+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF';
  const {pdfPage}=load('src/tingye/pdf-page.ts');fs.writeFileSync(path.join(out,'pdf.html'),pdfPage(Buffer.from(raw).toString('base64'),0,'Original PDF page\nSelectable text',config,fs.readFileSync('assets/reader/pdf.reader','utf8')));await page.goto('file:///'+path.join(out,'pdf.html').replaceAll('\\','/'));await page.waitForFunction(()=>window.messages.some(m=>m.type==='ready'||m.type==='error'));assert.ok(await page.locator('canvas').count());assert.ok((await page.locator('.textLayer').textContent()).includes('Selectable text'));await page.screenshot({path:path.join(out,'pdf.png')});assert.ok(!(await page.evaluate(()=>window.messages)).some(m=>m.type==='error'));
  assert.deepEqual(errors,[]);console.log('PASS: original EPUB CSS/imports, images, tables, selectable text, fixed pages, image-only pages, script/network isolation, all narration offsets visible, settings reflow, highlight and narrow viewport.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
